[package]
name = "ctdo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
chrono = "0.4.38"
crossterm = "0.28.1"
ratatui = { version = "0.28.1", features = ["all-widgets"] }
rusqlite = { version = "0.32.1", features = ["bundled", "chrono"] }
